language: r
cache:
  packages: true
  directories:
    - $HOME/.TinyTeX
latex: false
env:
  global:
    - PATH=$HOME/bin:$PATH
pandoc_version: 2.9.2.1
addons:
 apt:
   update: true
   sources:
     - sourceline: 'ppa:opencpu/imagemagick'
     - sourceline: 'ppa:cran/poppler'
   packages:
     - ghostscript
     - libmagick++-dev
     - libpoppler-cpp-dev

before_script:
  - wget -qO- https://yihui.org/tinytex/download-travis-linux.sh | sh
  - chmod +x ./_build.sh

script:
  - ./_build.sh
