language: r
cache: packages
pandoc_version: 2.9.2.1
addons:
 apt:
   update: true
   sources:
     - sourceline: 'ppa:opencpu/imagemagick'
     - sourceline: 'ppa:ubuntugis/ppa'
   packages:
     - ghostscript
     - libmagick++-dev
     - librsvg2-dev
     - libwebp-dev
     - libpoppler-cpp-dev
     - libtesseract-dev
     - libleptonica-dev
     - tesseract-ocr-eng
     - r-cran-rgdal
     - libfftw3-dev
     - cargo

before_script:
  - chmod +x ./_build.sh

script:
  - ./_build.sh
