# Reticular Action Model (RAM) Matrix Notation {#ram-matrix-notation}

\begin{equation}
  \mathbf{v}
  =
  \mathbf{A} \mathbf{v} + \mathbf{u}
\end{equation}

\noindent where

- $\mathbf{v}$ is a $t \times 1$ vector of random variables
- $u_i$ represent the residual of $v_i$
- $\mathbf{A}$ is a $t \times t$ matrix of *directed* or *asymmetric* relationship
  from column variable $v_j$ to row variable $v_i$
  - regression of each of the $t$ variables on the other $t - 1$ variables
  - diagonal $a_{i,i}$ is zero
  - if all regression coefficients on other variables are zero,
    then the variable $v_i$ is considered the same as its own residual $u_i$

\begin{equation}
  \boldsymbol{\Omega}
  =
  \mathbb{E}
  \left(
    \mathbf{u} \mathbf{u}^{\prime}
  \right)
\end{equation}

\noindent where

- $\boldsymbol{\Omega}$ is a $t \times t$ matrix of *undirected* or *symmetric* relationship

\begin{equation}
  \boldsymbol{\Sigma} \left( \boldsymbol{\theta} \right)
  =
  \left( \mathbf{I} - \mathbf{A} \right)^{-1}
  \boldsymbol{\Omega}
  \left[ \left( \mathbf{I} - \mathbf{A} \right)^{-1} \right]^{\mathsf{T}}
\end{equation}

- $\boldsymbol{\Sigma} \left( \boldsymbol{\theta} \right)$ is a $t \times t$ symmetric matrix
  of associations between $v_i$ and $v_j$

\begin{equation}
  \mathbf{v}^{\mathsf{T}}
  =
  \left[
    \mathbf{m}, \mathbf{l}
  \right]^{\mathsf{T}}
\end{equation}

\noindent where

- $\mathbf{m}$ are observed or manifest variables of $j$ components
- $\mathbf{l}$ are observed or manifest variables of $k$ components
- $t = j + k$

\begin{equation}
  \mathbf{F}
  =
  \left[
    \mathbf{I}_{j} \colon \mathbf{O}_{j \times k}
  \right]
\end{equation}

- the $\mathbf{F}$ acts as a filter to select the manifest variables
  out of the full set of manifest and latent variables

## Model-Implied Matrices

The model-implied mean vector
$\boldsymbol{\mu} \left( \boldsymbol{\theta} \right)$
as a function of Reticular Action Model (RAM) matrices
is given by

\begin{equation}
  \boldsymbol{\mu} \left( \boldsymbol{\theta} \right)
  =
  \mathbf{F}
  \left( \mathbf{I} - \mathbf{A} \right)^{-1}
  \mathbf{m} .
\end{equation}

\noindent The `ram::mutheta()` function can be used
to derive the model-implied mean vector.

The model-implied variance-covariance matrix
$\boldsymbol{\Sigma} \left( \boldsymbol{\theta} \right)$
as a function of Reticular Action Model (RAM) matrices
is given by

\begin{equation}
  \boldsymbol{\Sigma} \left( \boldsymbol{\theta} \right)
  =
  \mathbf{F}
  \left( \mathbf{I} - \mathbf{A} \right)^{-1}
  \boldsymbol{\Omega}
  \left[ \left( \mathbf{I} - \mathbf{A} \right)^{-1} \right]^{\mathsf{T}}
  \mathbf{F}^{\mathsf{T}} .
\end{equation}

\noindent The `ram::Sigmatheta()` function can be used
to derive the model-implied variance-covariance matrix.

## Parameters

### Mean Structure

\begin{equation}
  \mathbf{m}
  =
  \left[
    \mathbf{F}
    \left( \mathbf{I} - \mathbf{A} \right)^{-1}
  \right]^{-1}
  \boldsymbol{\mu} \left( \boldsymbol{\theta} \right)
\end{equation}

\noindent The `ram::m()` function can be used
to derive the mean structure vector.

### Covariance Structure

\begin{equation}
  \boldsymbol{\Omega}
  =
  \left( \mathbf{I} - \mathbf{A} \right)
  \boldsymbol{\Sigma} \left( \boldsymbol{\theta} \right)
  \left( \mathbf{I} - \mathbf{A} \right)^{\mathsf{T}}
\end{equation}

\noindent The `ram::Omega()` function can be used
to derive the *symmetric* matrix $\boldsymbol{\Omega}$.

TODO: Figure out how to isolate the A matrix
