if (!require("styler")) install.packages("styler")
if (!require("remotes")) install.packages("remotes")
if (!require("magick")) install.packages("magick")
if (!require("pdftools")) install.packages("pdftools")
if (!require("bookdown")) install.packages("bookdown")
if (!require("ram")) remotes::install_github("jeksterslab/ram")
styler::style_dir()
